version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "build Dockerfile"
          command:
            make master;
      - run:
          name: "Text docker images"
          command:
            make test;
      - run:
          name: "Push docker images"
          command: |
            echo "$DOCKER_PWD" | docker login --username kayuii --password-stdin
            make push;

  build-mass:
    machine: true
    steps:
      - checkout
      - run:
          name: "build Dockerfile"
          command:
            make mass;
      - run:
          name: "test docker images"
          command:
            make test;
      - run:
          name: "Push docker images"
          command: |
            echo "$DOCKER_PWD" | docker login --username kayuii --password-stdin
            make push;


workflows:
  myflow:
    jobs:
      - build:
          context: docker
          filters:
            branches:
              only: main
      - build-mass:
          context: docker
          filters:
            tags:
              only: /^mass-v.*/
            branches:
              ignore: /.*/
